# Generated by Django 2.1.5 on 2019-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='degree',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='password3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
