# Generated by Django 2.1.5 on 2019-12-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username_jp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
