# Generated by Django 2.1.5 on 2019-12-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191216_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password3',
        ),
    ]
