# Generated by Django 2.1.5 on 2019-12-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191216_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password3',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
